spring.application.name=bff-agendador-tarefas

usuario.url=${USUARIO_URL:localhost:8080/usuario}
agendador-tarefas.url=${AGENDADOR_TAREFAS_URL:localhost:8081/tarefas}
notificacao.url=${NOTIFICACAO_URL:localhost:8082/email}
server.port=8083

cron.horario=0/30 0/1 * * * ?

usuario.email=admin@admin.com
usuario.senha= ${USUARIO_SENHA:teste}

spring.cloud.openfeign.okhttp.enabled=true

server.forward-headers-strategy=native
